# Generated by Django 4.0.5 on 2022-07-07 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ball',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('B', 'Bridgestone'), ('C', 'Callaway'), ('H', 'Honma'), ('K', 'Kirkland'), ('M', 'Mizuno'), ('Sl', 'Slazenger'), ('Sr', 'Srixon'), ('Ta', 'Taylormade'), ('Ti', 'Titleist'), ('To', 'TopFlite'), ('Vi', 'Vice'), ('Vo', 'Volvik'), ('W', 'Wilson')], max_length=2)),
                ('description', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spin', models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], max_length=1)),
                ('feel', models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], max_length=1)),
                ('ball', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golf_ball_app.ball')),
            ],
        ),
    ]
