# Generated by Django 4.0.5 on 2022-07-07 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_ball_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='feel',
            field=models.CharField(choices=[('S', 'Soft'), ('F', 'Firm')], max_length=1),
        ),
    ]
