# Generated by Django 4.0.6 on 2022-07-08 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golf_ball_app', '0003_ball_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('B', 'Bridgestone'), ('C', 'Callaway'), ('H', 'Honma'), ('K', 'Kirkland'), ('M', 'Mizuno'), ('Sl', 'Slazenger'), ('Sr', 'Srixon'), ('Ta', 'Taylormade'), ('Ti', 'Titleist'), ('To', 'TopFlite'), ('Vi', 'Vice'), ('Vo', 'Volvik'), ('W', 'Wilson')], max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='ball',
        ),
        migrations.AddField(
            model_name='ball',
            name='attributes',
            field=models.ManyToManyField(to='golf_ball_app.attribute'),
        ),
        migrations.AlterField(
            model_name='ball',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golf_ball_app.brand'),
        ),
    ]
