# Generated by Django 4.0.6 on 2022-07-10 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_ball_app', '0004_brand_remove_attribute_ball_ball_attributes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ball',
            name='attributes',
        ),
        migrations.AddField(
            model_name='ball',
            name='feel',
            field=models.CharField(choices=[('S', 'Soft'), ('F', 'Firm')], default='', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ball',
            name='spin',
            field=models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Attribute',
        ),
    ]
