# Generated by Django 4.0.6 on 2022-07-10 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golf_ball_app', '0005_remove_ball_attributes_ball_feel_ball_spin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='brand',
            new_name='name',
        ),
    ]
