# Generated by Django 4.0.6 on 2022-07-11 07:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('golf_ball_app', '0006_rename_brand_brand_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ball',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
